name: aiblojka
description: "AI-powered video cover generation PWA."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.0
  firebase_analytics: ^11.4.4
  http: ^1.4.0
  intl: ^0.20.2
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.4.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.3.14

flutter:
  generate: true
  uses-material-design: true
